/**
 * Utilities for extracting checklist items from plan markdown.
 *
 * Plans generated by AI providers can contain structured steps in various
 * markdown formats (task lists, numbered lists, etc.). This module normalises
 * them into a uniform `PlanChecklistItem` shape so the UI can render a
 * consistent checklist experience regardless of the input format.
 */

export interface PlanChecklistItem {
  /** Stable key derived from the item text. */
  id: string;
  /** Display text for the item (markdown-level formatting stripped). */
  text: string;
  /** Whether the item was marked as completed in the source markdown. */
  completed: boolean;
}

/**
 * Extract checklist items from plan markdown.
 *
 * Supports three common patterns (in priority order):
 * 1. GitHub-flavoured task list items (`- [ ] …` / `- [x] …`)
 * 2. Numbered list items under a heading that looks like "steps" / "plan" / "todo"
 * 3. Any top-level numbered list items as a final fallback
 */
export function extractPlanChecklistItems(markdown: string): PlanChecklistItem[] {
  // Attempt 1: GFM task-list items
  const taskListItems = extractTaskListItems(markdown);
  if (taskListItems.length > 0) {
    return taskListItems;
  }

  // Attempt 2: numbered items under a step-like heading
  const headingItems = extractNumberedItemsUnderStepHeading(markdown);
  if (headingItems.length > 0) {
    return headingItems;
  }

  // Attempt 3: any top-level numbered list
  const numberedItems = extractTopLevelNumberedItems(markdown);
  if (numberedItems.length > 0) {
    return numberedItems;
  }

  return [];
}

// ---------------------------------------------------------------------------
// Parsers
// ---------------------------------------------------------------------------

const TASK_LIST_RE = /^[ \t]*[-*]\s+\[([ xX])\]\s+(.+)$/gm;

function extractTaskListItems(markdown: string): PlanChecklistItem[] {
  const items: PlanChecklistItem[] = [];
  let match: RegExpExecArray | null;
  TASK_LIST_RE.lastIndex = 0;

  while ((match = TASK_LIST_RE.exec(markdown)) !== null) {
    const completed = match[1]?.toLowerCase() === "x";
    const rawText = match[2]?.trim() ?? "";
    if (rawText.length === 0) continue;
    items.push({
      id: stableItemId(rawText, items.length),
      text: stripInlineMarkdown(rawText),
      completed,
    });
  }

  return items;
}

const STEP_HEADING_RE =
  /^\s{0,3}#{1,6}\s+.*(?:step|plan|todo|task|checklist|order\s+of\s+execution|implementation)/im;
const HEADING_RE = /^\s{0,3}#{1,6}\s+/m;
const NUMBERED_ITEM_RE = /^\s{0,3}\d+[.)]\s+(.+)$/gm;

function extractNumberedItemsUnderStepHeading(markdown: string): PlanChecklistItem[] {
  const headingMatch = STEP_HEADING_RE.exec(markdown);
  if (!headingMatch) return [];

  // Slice from the heading to the next heading (or end of document).
  const startIndex = headingMatch.index + headingMatch[0].length;
  const rest = markdown.slice(startIndex);
  const nextHeadingMatch = HEADING_RE.exec(rest);
  const sectionText = nextHeadingMatch ? rest.slice(0, nextHeadingMatch.index) : rest;

  return parseNumberedItems(sectionText);
}

function extractTopLevelNumberedItems(markdown: string): PlanChecklistItem[] {
  return parseNumberedItems(markdown);
}

function parseNumberedItems(text: string): PlanChecklistItem[] {
  const items: PlanChecklistItem[] = [];
  let match: RegExpExecArray | null;
  NUMBERED_ITEM_RE.lastIndex = 0;

  while ((match = NUMBERED_ITEM_RE.exec(text)) !== null) {
    const rawText = match[1]?.trim() ?? "";
    if (rawText.length === 0) continue;
    items.push({
      id: stableItemId(rawText, items.length),
      text: stripInlineMarkdown(rawText),
      completed: false,
    });
  }

  return items;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Strip common inline markdown formatting (bold, italic, code, links). */
function stripInlineMarkdown(text: string): string {
  return (
    text
      // Bold + italic: ***text*** or ___text___
      .replace(/(\*{3}|_{3})(.+?)\1/g, "$2")
      // Bold: **text** or __text__
      .replace(/(\*{2}|_{2})(.+?)\1/g, "$2")
      // Italic: *text* or _text_
      .replace(/(\*|_)(.+?)\1/g, "$2")
      // Inline code
      .replace(/`([^`]+)`/g, "$1")
      // Links: [text](url)
      .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
      .trim()
  );
}

/** Produce a stable id from the item text + index. */
function stableItemId(text: string, index: number): string {
  const slug = text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 48);
  return `plan-item-${index}-${slug}`;
}
