/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as ChatSettingsRouteImport } from './routes/_chat.settings'
import { Route as ChatPrReviewRouteImport } from './routes/_chat.pr-review'
import { Route as ChatMergeConflictsRouteImport } from './routes/_chat.merge-conflicts'
import { Route as ChatFileViewRouteImport } from './routes/_chat.file-view'
import { Route as ChatThreadIdRouteImport } from './routes/_chat.$threadId'

const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatSettingsRoute = ChatSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ChatRoute,
} as any)
const ChatPrReviewRoute = ChatPrReviewRouteImport.update({
  id: '/pr-review',
  path: '/pr-review',
  getParentRoute: () => ChatRoute,
} as any)
const ChatMergeConflictsRoute = ChatMergeConflictsRouteImport.update({
  id: '/merge-conflicts',
  path: '/merge-conflicts',
  getParentRoute: () => ChatRoute,
} as any)
const ChatFileViewRoute = ChatFileViewRouteImport.update({
  id: '/file-view',
  path: '/file-view',
  getParentRoute: () => ChatRoute,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/$threadId': typeof ChatThreadIdRoute
  '/file-view': typeof ChatFileViewRoute
  '/merge-conflicts': typeof ChatMergeConflictsRoute
  '/pr-review': typeof ChatPrReviewRoute
  '/settings': typeof ChatSettingsRoute
}
export interface FileRoutesByTo {
  '/$threadId': typeof ChatThreadIdRoute
  '/file-view': typeof ChatFileViewRoute
  '/merge-conflicts': typeof ChatMergeConflictsRoute
  '/pr-review': typeof ChatPrReviewRoute
  '/settings': typeof ChatSettingsRoute
  '/': typeof ChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/_chat/$threadId': typeof ChatThreadIdRoute
  '/_chat/file-view': typeof ChatFileViewRoute
  '/_chat/merge-conflicts': typeof ChatMergeConflictsRoute
  '/_chat/pr-review': typeof ChatPrReviewRoute
  '/_chat/settings': typeof ChatSettingsRoute
  '/_chat/': typeof ChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$threadId'
    | '/file-view'
    | '/merge-conflicts'
    | '/pr-review'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/$threadId' | '/file-view' | '/merge-conflicts' | '/pr-review' | '/settings' | '/'
  id:
    | '__root__'
    | '/_chat'
    | '/_chat/$threadId'
    | '/_chat/file-view'
    | '/_chat/merge-conflicts'
    | '/_chat/pr-review'
    | '/_chat/settings'
    | '/_chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/settings': {
      id: '/_chat/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ChatSettingsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/pr-review': {
      id: '/_chat/pr-review'
      path: '/pr-review'
      fullPath: '/pr-review'
      preLoaderRoute: typeof ChatPrReviewRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/merge-conflicts': {
      id: '/_chat/merge-conflicts'
      path: '/merge-conflicts'
      fullPath: '/merge-conflicts'
      preLoaderRoute: typeof ChatMergeConflictsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/file-view': {
      id: '/_chat/file-view'
      path: '/file-view'
      fullPath: '/file-view'
      preLoaderRoute: typeof ChatFileViewRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$threadId': {
      id: '/_chat/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatFileViewRoute: typeof ChatFileViewRoute
  ChatMergeConflictsRoute: typeof ChatMergeConflictsRoute
  ChatPrReviewRoute: typeof ChatPrReviewRoute
  ChatSettingsRoute: typeof ChatSettingsRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatFileViewRoute: ChatFileViewRoute,
  ChatMergeConflictsRoute: ChatMergeConflictsRoute,
  ChatPrReviewRoute: ChatPrReviewRoute,
  ChatSettingsRoute: ChatSettingsRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
