import { describe, expect, it } from "vitest";

import {
  sanitizeGeneratedCommitBody,
  sanitizeGeneratedCommitSubject,
  sanitizeGeneratedPrBody,
  sanitizeGeneratedPrTitle,
} from "./generatedTextSanitization.ts";

describe("generatedTextSanitization", () => {
  it("removes provider attribution trailers from generated commit bodies", () => {
    expect(
      sanitizeGeneratedCommitBody(
        [
          "- Add server-side fallback",
          "",
          "Generated with [Claude Code](https://claude.ai/code)",
          "Co-authored-by: Codex <noreply@openai.com>",
        ].join("\n"),
      ),
    ).toBe("- Add server-side fallback");
  });

  it("falls back when the generated commit subject is only provider attribution", () => {
    expect(sanitizeGeneratedCommitSubject("Generated with Claude Code")).toBe(
      "Update project files",
    );
  });

  it("removes provider attribution notes from generated PR bodies", () => {
    expect(
      sanitizeGeneratedPrBody(
        [
          "## Summary",
          "- Tighten generated git text sanitizing",
          "",
          "## Testing",
          "- Not run",
          "",
          "Generated by OpenAI Codex",
          "Co-authored-by: Claude Opus 4.6 <noreply@anthropic.com>",
        ].join("\n"),
      ),
    ).toBe(
      ["## Summary", "- Tighten generated git text sanitizing", "", "## Testing", "- Not run"].join(
        "\n",
      ),
    );
  });

  it("falls back when the generated PR title is only provider attribution", () => {
    expect(sanitizeGeneratedPrTitle("Generated by OpenAI Codex")).toBe("Update project changes");
  });

  it("does not strip normal summary lines that mention providers in prose", () => {
    expect(
      sanitizeGeneratedPrBody(
        [
          "## Summary",
          "- Document OpenAI provider failover behavior",
          "",
          "## Testing",
          "- Not run",
        ].join("\n"),
      ),
    ).toBe(
      [
        "## Summary",
        "- Document OpenAI provider failover behavior",
        "",
        "## Testing",
        "- Not run",
      ].join("\n"),
    );
  });
});
